### ISSUE TITLE
部分翻译问题

### ISSUE THREAD

**Issue by qsdgy** [zjp-CN/api-guidelines#3]
3
`生成条目的宏应支持可视分类符` => `生成条目的宏应支持可见性分类符`
`宏应遵循 Rust 对条目可视化 (visibility) 的语法要求` => `宏应遵循 Rust 对条目可见性 (visibility) 的语法要求`  
[Rust 语言术语中英文对照表](https://github.com/rust-lang-cn/english-chinese-glossary-of-rust/blob/master/rust-glossary.md)
4
`可以或者可能导致 panic 的方法都应该在 "Errors" 小节进行说明`=>`可以或者可能导致 panic 的方法都应该在 "Panics" 小节进行说明`
5
`方法可以轻松回答 “如何处理具有泛型 T 的值” 的问题` =>`方法可以轻松回答 “如何处理类型 T 的值” 的问题` 
~~`String 是 str 的智能指针` => `str 是 String 的智能指针`~~
6
`异质性：当你需要 trait object 的时候，不一定真的需要它。`=>`异质性：当你需要 trait object 的时候，确实真的需要它。`
7
`下面这个函数不出意外地会调用 Kilometers 类型的值。`=>`下面这个函数不会意外地传入 Kilometers 类型的值。`
8
`考虑提供单独的方法来为意外做万无一失而畅通无阻的准备`=>`考虑为不会失败且非阻塞的析构提供单独的方法`
10
`属性里的每个 trait 都会展开成单独的、给这个泛型参数实现 trait 的 impl 块`=>`属性里的每个 trait 都只对实现了此 trait 的泛型参数展开成单独的 impl 块`
11
`所以这个有许可证的 crate 通常应该信赖 有许可证的 crates 。`=>`所以 自由许可 的 crate 通常应仅依赖 自由许可 的 crates 。`

**Comment by zjp-CN** [comment]
@qsdgy 有啥问题吗。。。

**Comment by qsdgy** [comment]
@zjp-CN 看一下

**Comment by zjp-CN** [comment]
@qsdgy 
谢谢指出这些错误，现在都改好了。除了下面这个：

>String is a smart pointer to str

翻译成 “String 是 str 的智能指针” 没问题啊。

**Comment by qsdgy** [comment]
@zjp-CN 没错，是我对 String 和 str 的理解出了问题
